import { CheckCircleIcon, LightBulbIcon } from '@heroicons/react/24/outline'
import React, { useEffect, useState } from 'react'
import Navbar from './Navbar'

function TOTM() {
    const [steps, setSteps] = useState([
        {name:'January', status:'current',tip:'January: Review the Accuracy of Medication Orders for patient, Medication, and Dosage', background:'This Tip comes from two cases. In the first case, the physician inadvertently entered an order for a diabetic patient into a non-diabetic patient’s chart in the electronic record. The non-diabetic patient became hypoglycemic and died. In the second case, the physician inadvertently prescribed the wrong dosage of medication when the physician clicked on a higher dosage than the physician had intended when accessing the electronic  record. Additionally, the physician did not review the physical prescription generated by the computer prior to handing it to the patient. The physician later learned that the patient had died as a result of the medication and, in particular, its dosage. ',conclusion:'Review all medication orders prior to submission to ensure accuracy. At a minimum, this should include verifying that the order is for the right patient, the intended medication, and the proper dosage.'},
        {name:'February', status:'upcoming',tip:'February: Ensure a System Is in Place to Follow-Up on All Test Results', background:'In one case, a patient underwent a CT scan of the chest while in the ED. The CT revealed a lung nodule and the result was communicated to the ED resident after the patient was admitted to the hospital. The resident assumed those now caring for the patient would see the report of the CT scan  and follow up on it. A PA on the unit housing the patient was the only one to see the report and to write  a note in the chart relative to the results. However, the PA did not communicate the results to the attending physician and the attending failed to see the PA’s note. The patient did not learn of the presence of lung cancer until nine months later. In a second case, a patient underwent incidental testing, including a chest X-ray, prior to undergoing  a prostatectomy. The chest X-ray revealed a lung nodule. The urologist who performed the surgery  had been referred to the patient for the specific procedure. Therefore, the surgeon assumed that all pre-op testing had been reviewed by the referring urologist. The patient had a significant cardiac  history; hence, the referring urologist had insisted the patient obtain clearance for the procedure from  his internist. As a result, the referring urologist assumed that all pre-op testing—including the chest Xray—had been reviewed by the patient’s internist. The result was that no one made note of, or acted upon, the incidental chest X-ray result and lung cancer was not diagnosed until 10 months later. ', conclusion:'An attending physician is obligated to review the progress notes and to follow up on studies when necessary. Furthermore, it is essential that admitting/attending physicians review all preadmission/pre-op testing. It does not matter whether a finding on a study was incidental or unrelated to the purpose of the hospital admission.'},
        {name:'March', status:'upcoming',tip:'March: Being Inappropriately Deferential Can Create Liability ', background:'A 60-year-old patient developed deep vein thrombosis following surgery and received Coumadin. The INR and associated Coumadin levels should have been closely monitored by the patient’s internist. However, the internist assumed that because both the patient and the patient’s spouse were physicians, and the spouse was actively drawing blood and bringing it to the hospital for analysis, that the internist was not responsible for overseeing the administration of Coumadin, monitoring the INR levels, or documenting changes in medications. Despite the fact that the defendant was the patient’s  internist, the defendant could not testify as to the patient’s INR levels or to changes in the patient’s medication because neither of these were documented by the defendant. The patient died as a result of an emboli and the responsibility was clearly upon the shoulders of the defendant internist. ',conclusion:'A patient’s attending physician is responsible for overseeing and documenting the patient’s care and treatment. That responsibility cannot be mitigated because the patient or the patient’s immediate family  member happens to be a physician as well.'}])
       const [currentStep, setCurrentStep] = useState(steps[0])
      
   
    function handleStepChange(month){
 
        setSteps(steps.map((step,stepIdx)=>{
            var tempStep = step
            if(step?.name.toLowerCase() === month){
                tempStep.status = 'current'
                setCurrentStep(tempStep)

            }else{
                tempStep.status = 'upcoming'
                
            }
            return tempStep
        }))
      
        
     
    }
    function handleStepClick(e){
        switch (e.target.id) {
            case 'January':
                
            handleStepChange('january')
                break;
                case 'February':
                
                handleStepChange('february')
                    break;
                    case 'March':
                
                handleStepChange('march')
                    break;
                    
            
        
            default:
                break;
        }
    }
    useEffect(() => {
     console.log(currentStep)
    }, [currentStep])
    
  return (
    <div >
        <Navbar/>
        <div class = 'body' className='flex pt-[103px]'>
        <div className="px-4 py-12 sm:px-6 lg:px-8">
      <nav className="flex justify-center" aria-label="Progress">
        <ol role="list" className="">
          {Object.values(steps).map((step) => {
            console.log(step)
            return(<li key={step.name} className={`p-2 ${currentStep?.name.toLowerCase()===step?.name.toLowerCase()?`border-r-[2px]  border-red-600`:`border-r-[2px] border-gray-300`}`} >
            {step.status === 'complete' ? (
              <a className="group hover:text-gray-300" >
                <span className="flex items-start ">
                  <span className="relative flex h-5 w-5 flex-shrink-0 items-center justify-center ">
                    <CheckCircleIcon
                      className="h-full w-full text-red-600 group-hover:text-red-800"
                      aria-hidden="true"
                    />
                  </span>
                  <span id={step?.name} onClick={(e)=>handleStepClick(e)} className="ml-3 text-sm font-medium text-gray-500 group-hover:text-gray-900 ">
                    {step.name}
                  </span>
                </span>
              </a>
            ) : step.status === 'current' ? (
              <a   className="flex items-start" aria-current="step">
                <span className="relative flex h-5 w-5 flex-shrink-0 items-center justify-center" aria-hidden="true">
                  <span className="absolute h-4 w-4 rounded-full bg-red-200" />
                  <span className="relative block h-2 w-2 rounded-full bg-red-600" />
                </span>
                <span id={step?.name} onClick={(e)=>handleStepClick(e)} className="ml-3 text-sm font-medium text-red-600">{step.name}</span>
              </a>
            ) : (
              <a  className="group">
                <div className="flex items-start">
                  <div className="relative flex h-5 w-5 flex-shrink-0 items-center justify-center" aria-hidden="true">
                    <div className="h-2 w-2 rounded-full bg-gray-300 group-hover:bg-gray-400" />
                  </div>
                  <p id={step?.name} onClick={(e)=>handleStepClick(e)} className="ml-3 text-sm font-medium text-gray-500 group-hover:text-gray-900">{step.name}</p>
                </div>
              </a>
            )}
          </li>)
            
})}
        </ol>
      </nav>
    </div>

    
<div class= 'content' className='flex-1 min-h-screen'>
    <div className = 'py-12 mx-4 md:mx-32 2xl:mx-64 h-full'>
        <div className='flex items-center'>
            <LightBulbIcon className='w-6 text-red-600'/>
        <h1>Tip of the Month</h1>
        </div>
       
    <h1 className='text-3xl py-2 font-bold border-b-[1px] mb-0 border-black'>
  {currentStep?.tip}
</h1>
<div className = 'my-6      '>
<h1 className = 'font-semibold my-2 text-red-600 '>
    Background
</h1>
<p className=''>
    {currentStep?.background}
</p>
</div>
<div className = 'my-6 '>
<h1 className = 'font-semibold my-2 text-red-600 '>
    Conclusion
</h1>
<p className='' >
    {currentStep?.conclusion}
</p>

</div>

<div className='my-16 w-fit  text-sm font-light'>
    <img className='w-40' src="https://www.healthcareriskadvisors.com/siteassets/images/13225_sbu-logos_hra_red-blk_300x73.png" alt="" />
    <p className=''> 
    Peter A. Kolbert
    </p>
    <p>
    Senior Vice President, Chief Claims Officer 
    </p>
    <p>
    Claim & Litigation Services 

    </p>
    <p>
    FOJP Service Corporation
    </p>
    <p>
    111 West 33rd Street, 8th floor 

    </p>
    <p>
    New York, NY 10120 

    </p>
    <p>
    P: 212.891.0733 
    </p>
    <p>pkolbert@tdchra.com</p>
</div>
    </div>

</div>

        </div>
    </div>
  )
}

export default TOTM